snowflake:
  account: 
  user: 
  password: 
  role: 
  warehouse: 

semantic_model:
  name: sample_analytics
  base_tables:
    - 
  n_sample_values: 4
  allow_joins: true

# llm: 
#   provider: cortex
#   model: llama3-8b
    
  
# Example OpenAI configuration
# llm:
#   provider: openai
#   model: gpt-4
#   api_key: your_openai_api_key
#   temperature: 0.2
#   max_tokens: 500

# Example Azure OpenAI configuration
# llm:
#   provider: azure_openai
#   azure_deployment_name: 
#   api_key: 
#   api_endpoint: 
#   api_version: 
#   temperature: 
#   max_tokens: 

# Example Anthropic configuration
# llm:
#   provider: anthropic
#   model: claude-3-sonnet-20240229
#   api_key: your_anthropic_api_key
#   temperature: 0.2
#   max_tokens: 500 